version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mdp4db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
  app:
    build: ./docker/app
    ports:
      - 8000
    volumes:
      - ./app:/var/www
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www"]
    environment:
      DATABASE_URL: mysql://root:mdp4db@db:3306/app
